spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 9199
    url: jdbc:mysql://localhost:3306/product_db
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true